"""
Django settings for DynamicOCR project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from celery.concurrency import custom
from decouple import config
# import dj_database_url
import environ
from celery.schedules import crontab

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, True),  # set casting, default value
    SERVER_NAME=(str, 'dev'),
    REDIS=(bool, False),
    REDIS_URL=(str, 'redis://localhost:6379/0'),
    APP_PORT=(str, '8000'),
    DAPHNE_PORT=(str, ''),
)
environ.Env.read_env() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

GEOIP_DATABASE = BASE_DIR / "geoip" / "GeoLite2-City.mmdb"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    # dj-rest-auth
    'dj_rest_auth.registration',
    'dj_rest_auth',
    'rest_framework.authtoken',

    'system',
    'accounts',
    'Qr',
    'analytics',
    "subscriptions"
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
#
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_EMAIL_VERIFICATION = 'none'

# ACCOUNT_SIGNUP_FIELDS = [
#     "email*",
#     "password1*",
#     "password2*",
# ]

ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none'

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": config("GOOGLE_CLIENT_ID", default=""),
                "secret": config("GOOGLE_CLIENT_SECRET", default=""),
                "key": "",
                "settings": {
                    "scope": ["profile", "email"],
                    "auth_params": {
                        "access_type": "online",
                        "prompt": "consent",
                    },
                },
            }
        ],
    }
}

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "accounts.adapters.GoogleFirstExistingUserSocialAccountAdapter"

GOOGLE_OAUTH2_CALLBACK_URL = config(
    "GOOGLE_OAUTH2_CALLBACK_URL",
    default="http://localhost:8000/api/v1.1/user/accounts/google/login/complete/",
)

LOGIN_REDIRECT_URL = config(
    "LOGIN_REDIRECT_URL",
    default="/api/v1.1/user/accounts/google/login/complete/",
)

# GOOGLE_ALLOWED_FRONTEND_CALLBACKS = [
#     "http://localhost:3000/auth/google/callback",
#     "http://localhost:5173/auth/google/callback",
#     "https://dev-qrnepal.vercel.app/auth/google/callback",
#     "https://qrnepal.vercel.app/auth/google/callback",
# ]
GOOGLE_FRONTEND_CALLBACK = "https://qrpac.com/auth/google/callback"
SOCIALACCOUNT_LOGIN_ON_GET = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    "http://localhost:5173",
    "http://localhost:4173",
    "https://cs-qrgen.vercel.app",
    "https://qrpack.vercel.app",
    "https://qrpac.com",
    "http://qrpac.com",
    "https://less-approach-farming-cultures.trycloudflare.com",
    "https://dev-qrnepal.vercel.app",
    "https://qrpac.vercel.app"

]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    "http://localhost:5173",
    "http://localhost:4173",
    "https://qrpack.vercel.app",
    "https://qrnepal.vercel.app",
    "https://dev-qrnepal.vercel.app",
    "https://qrpac.vercel.app",
    "https://qrpac.com",
    "http://qrpac.com",
    "https://less-approach-farming-cultures.trycloudflare.com"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

AUTH_USER_MODEL = "accounts.User"

ROOT_URLCONF = 'DynamicOCR.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DynamicOCR.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': env.db()  # psql://user:pass@127.0.0.1:8458/db
}
DATABASES = {
    'default': {
        **env.db(),  # Loads DATABASE_URL from environment
        'CONN_MAX_AGE': 0,  # Reuse connections for 300 seconds
    }
}
#postgresql://username:password@localhost:5432/mydatabase

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'DynamicOCR.pagination.CustomPagination',
    'PAGE_SIZE': 10,
}





EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = True

EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# from decouple import config
#
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_HTTPONLY = False  # False so frontend can read it if needed
#
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_SAMESITE = 'None'

REFRESH_COOKIE_DOMAIN = config("REFRESH_COOKIE_DOMAIN", default=None)

FRONTEND_URL = config("FRONTEND_URL", default=None)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
CUSTOM_DOMAIN_CNAME_TARGET="qrpac.com"
BASE_DOMAIN="qrpac.com"
DODO_PAYMENTS_API_KEY = config("DODO_API_KEY", default=None)
# print(DODO_PAYMENTS_API_KEY)
# DODO_SUBSCRIPTION_PRODUCT_ID = config("DODO_SUBSCRIPTION_PRODUCT_ID", default="pdt_0NmevMBs1Ny7Ol2lzyq3H")
LETSENCRYPT_EMAIL = "bhubanghimire3130@gmail.com"

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=env("REDIS_URL"))
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=env("REDIS_URL"))
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    "process-due-subscription-renewals": {
        "task": "subscriptions.tasks.process_due_subscription_renewals",
        "schedule": 300,
    }
    ,
    "send-weekly-notification-digest": {
        "task": "accounts.tasks.send_weekly_notification_digest",
        "schedule": crontab(minute=0, hour=9, day_of_week=6),
    },
}

# DNS Settings
DNS_NAMESERVERS = [
    "1.1.1.1",  # Cloudflare
    "8.8.8.8",  # Google
    "9.9.9.9",  # Quad9
]

# Nginx Settings
NGINX_CLIENT_MAX_BODY_SIZE = "50M"
BACKEND_HOST = "127.0.0.1:8001"
PROXY_CONNECT_TIMEOUT = "60s"
PROXY_SEND_TIMEOUT = "120s"
PROXY_READ_TIMEOUT = "120s"
DODO_WEBHOOK_SECRET = os.environ.get('DODO_WEBHOOK_SECRET', '')
DODO_PRODUCT_TAX_CATEGORY = config(
    "DODO_PRODUCT_TAX_CATEGORY",
    default="saas",
)
CUSTOM_DOMAIN_IP = os.environ.get('CUSTOM_DOMAIN_IP', '')
