import os
import subprocess
import logging
from jinja2 import Template
from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)


class NginxConfigService:
    """Service for managing Nginx configurations for React frontend domains"""

    NGINX_TEMPLATE = """
# Nginx configuration for {{ domain }}
# Auto-generated by QR System - {{ generated_at }}

server {
    listen 80;
    listen [::]:80;

    server_name {{ domain }};

    root /var/www/qrpac;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /favicon.svg {
        access_log off;
        log_not_found off;
    }
}
"""

    def __init__(self, domain_obj):
        self.domain_obj = domain_obj
        self.domain = domain_obj.domain
        self.config_path = f"/etc/nginx/sites-available/{self.domain}.conf"
        self.enabled_path = f"/etc/nginx/sites-enabled/{self.domain}.conf"

    def generate_config(self, context=None):
        """Generate Nginx configuration from template"""
        default_context = {
            'domain': self.domain,
            'generated_at': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
            'root':'/var/www/qrpac',
        }

        if context:
            default_context.update(context)

        template = Template(self.NGINX_TEMPLATE)
        return template.render(**default_context)

    def write_config(self, context=None):
        """Write Nginx configuration to file"""
        try:
            config_content = self.generate_config(context)

            # Ensure directory exists
            os.makedirs('/etc/nginx/sites-available/', exist_ok=True)

            with open(self.config_path, 'w') as f:
                f.write(config_content)

            logger.info(f"Nginx config written for {self.domain} at {self.config_path}")
            return {'success': True, 'path': self.config_path}
        except Exception as e:
            logger.error(f"Failed to write Nginx config for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def enable_site(self):
        """Enable the site by creating symlink"""
        try:
            if os.path.exists(self.enabled_path):
                return {'success': True, 'message': 'Site already enabled'}

            os.symlink(self.config_path, self.enabled_path)
            logger.info(f"Nginx site enabled for {self.domain}")
            return {'success': True, 'path': self.enabled_path}
        except Exception as e:
            logger.error(f"Failed to enable Nginx site for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def disable_site(self):
        """Disable the site by removing symlink"""
        try:
            if os.path.exists(self.enabled_path):
                os.remove(self.enabled_path)
                logger.info(f"Nginx site disabled for {self.domain}")
            return {'success': True}
        except Exception as e:
            logger.error(f"Failed to disable Nginx site for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def remove_config(self):
        """Remove configuration file"""
        try:
            if os.path.exists(self.config_path):
                os.remove(self.config_path)
                logger.info(f"Nginx config removed for {self.domain}")
            return {'success': True}
        except Exception as e:
            logger.error(f"Failed to remove Nginx config for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    @staticmethod
    def test_nginx():
        """Test Nginx configuration"""
        try:
            result = subprocess.run(
                ['nginx', '-t'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                return {'success': True, 'output': result.stdout}
            else:
                return {'success': False, 'error': result.stderr}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @staticmethod
    def reload_nginx():
        """Reload Nginx service"""
        try:
            result = subprocess.run(
                ['systemctl', 'reload', 'nginx'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                return {'success': True}
            else:
                return {'success': False, 'error': result.stderr}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @staticmethod
    def full_nginx_reload():
        """Full Nginx reload (test + reload)"""
        test_result = NginxConfigService.test_nginx()
        if not test_result['success']:
            return test_result

        return NginxConfigService.reload_nginx()