# services/nginx_config_service.py
import os
import subprocess
import logging
from jinja2 import Template
from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)


class NginxConfigService:
    """Service for managing Nginx configurations for custom domains"""

    NGINX_TEMPLATE = """
# Nginx configuration for {{ domain }}
# Auto-generated by QR System - {{ generated_at }}

# HTTP → HTTPS Redirect
server {
    listen 80;
    listen [::]:80;
    server_name {{ domain }};

    # Redirect to HTTPS
    return 301 https://$server_name$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {{ domain }};

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size {{ client_max_body_size|default('50M') }};
    server_tokens off;

    # Logs
    access_log /var/log/nginx/{{ domain }}-access.log;
    error_log /var/log/nginx/{{ domain }}-error.log warn;

    # Static files (if using Django's static)
    location /static/ {
        alias {{ static_root|default('/root/DynamicQR/staticfiles/') }};
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Media files (if using Django's media)
    location /media/ {
        alias {{ media_root|default('/root/DynamicQR/media/') }};
        expires 7d;
        add_header Cache-Control "public";
        access_log off;
    }

    # Proxy to Django backend
    location / {
        proxy_pass http://{{ backend_host|default('127.0.0.1:8001') }};
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_connect_timeout {{ proxy_connect_timeout|default('60s') }};
        proxy_send_timeout {{ proxy_send_timeout|default('120s') }};
        proxy_read_timeout {{ proxy_read_timeout|default('120s') }};

        proxy_buffering on;
        proxy_buffer_size 16k;
        proxy_buffers 8 16k;
        proxy_busy_buffers_size 32k;

        proxy_redirect off;
    }
}
"""

    def __init__(self, domain_obj):
        self.domain_obj = domain_obj
        self.domain = domain_obj.domain
        self.config_path = f"/etc/nginx/sites-available/{self.domain}.conf"
        self.enabled_path = f"/etc/nginx/sites-enabled/{self.domain}.conf"

    def generate_config(self, context=None):
        """Generate Nginx configuration from template"""
        default_context = {
            'domain': self.domain,
            'generated_at': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
            'client_max_body_size': getattr(settings, 'NGINX_CLIENT_MAX_BODY_SIZE', '50M'),
            'static_root': getattr(settings, 'STATIC_ROOT', '/root/DynamicQR/staticfiles/'),
            'media_root': getattr(settings, 'MEDIA_ROOT', '/root/DynamicQR/media/'),
            'backend_host': getattr(settings, 'BACKEND_HOST', '127.0.0.1:8001'),
            'proxy_connect_timeout': getattr(settings, 'PROXY_CONNECT_TIMEOUT', '60s'),
            'proxy_send_timeout': getattr(settings, 'PROXY_SEND_TIMEOUT', '120s'),
            'proxy_read_timeout': getattr(settings, 'PROXY_READ_TIMEOUT', '120s'),
        }

        if context:
            default_context.update(context)

        template = Template(self.NGINX_TEMPLATE)
        return template.render(**default_context)

    def write_config(self, context=None):
        """Write Nginx configuration to file"""
        try:
            config_content = self.generate_config(context)

            # Ensure directory exists
            os.makedirs('/etc/nginx/sites-available/', exist_ok=True)

            with open(self.config_path, 'w') as f:
                f.write(config_content)

            logger.info(f"Nginx config written for {self.domain} at {self.config_path}")
            return {'success': True, 'path': self.config_path}
        except Exception as e:
            logger.error(f"Failed to write Nginx config for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def enable_site(self):
        """Enable the site by creating symlink"""
        try:
            if os.path.exists(self.enabled_path):
                return {'success': True, 'message': 'Site already enabled'}

            os.symlink(self.config_path, self.enabled_path)
            logger.info(f"Nginx site enabled for {self.domain}")
            return {'success': True, 'path': self.enabled_path}
        except Exception as e:
            logger.error(f"Failed to enable Nginx site for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def disable_site(self):
        """Disable the site by removing symlink"""
        try:
            if os.path.exists(self.enabled_path):
                os.remove(self.enabled_path)
                logger.info(f"Nginx site disabled for {self.domain}")
            return {'success': True}
        except Exception as e:
            logger.error(f"Failed to disable Nginx site for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    def remove_config(self):
        """Remove configuration file"""
        try:
            if os.path.exists(self.config_path):
                os.remove(self.config_path)
                logger.info(f"Nginx config removed for {self.domain}")
            return {'success': True}
        except Exception as e:
            logger.error(f"Failed to remove Nginx config for {self.domain}: {str(e)}")
            return {'success': False, 'error': str(e)}

    @staticmethod
    def test_nginx():
        """Test Nginx configuration"""
        try:
            result = subprocess.run(
                ['nginx', '-t'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                return {'success': True, 'output': result.stdout}
            else:
                return {'success': False, 'error': result.stderr}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @staticmethod
    def reload_nginx():
        """Reload Nginx service"""
        try:
            result = subprocess.run(
                ['systemctl', 'reload', 'nginx'],
                capture_output=True,
                text=True
            )
            if result.returncode == 0:
                return {'success': True}
            else:
                return {'success': False, 'error': result.stderr}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @staticmethod
    def full_nginx_reload():
        """Full Nginx reload (test + reload)"""
        test_result = NginxConfigService.test_nginx()
        if not test_result['success']:
            return test_result

        return NginxConfigService.reload_nginx()